// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BackupIndexNow() {
  return window['go']['main']['App']['BackupIndexNow']();
}

export function CancelTransfer(arg1) {
  return window['go']['main']['App']['CancelTransfer'](arg1);
}

export function ChangePassphrase(arg1, arg2) {
  return window['go']['main']['App']['ChangePassphrase'](arg1, arg2);
}

export function CreateAccount(arg1) {
  return window['go']['main']['App']['CreateAccount'](arg1);
}

export function DeleteEntries(arg1, arg2) {
  return window['go']['main']['App']['DeleteEntries'](arg1, arg2);
}

export function DownloadTo(arg1, arg2) {
  return window['go']['main']['App']['DownloadTo'](arg1, arg2);
}

export function EnsureFolder(arg1) {
  return window['go']['main']['App']['EnsureFolder'](arg1);
}

export function FileInfo(arg1) {
  return window['go']['main']['App']['FileInfo'](arg1);
}

export function GetAppState() {
  return window['go']['main']['App']['GetAppState']();
}

export function GetFolderMeta(arg1) {
  return window['go']['main']['App']['GetFolderMeta'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetThumbnail(arg1) {
  return window['go']['main']['App']['GetThumbnail'](arg1);
}

export function GetWebDAVConfig() {
  return window['go']['main']['App']['GetWebDAVConfig']();
}

export function ImportFromRemote(arg1) {
  return window['go']['main']['App']['ImportFromRemote'](arg1);
}

export function ListFolder(arg1) {
  return window['go']['main']['App']['ListFolder'](arg1);
}

export function Lock() {
  return window['go']['main']['App']['Lock']();
}

export function MoveFiles(arg1, arg2) {
  return window['go']['main']['App']['MoveFiles'](arg1, arg2);
}

export function PickDir() {
  return window['go']['main']['App']['PickDir']();
}

export function PickFiles() {
  return window['go']['main']['App']['PickFiles']();
}

export function PreviewGC() {
  return window['go']['main']['App']['PreviewGC']();
}

export function RunGC() {
  return window['go']['main']['App']['RunGC']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SaveWebDAVConfig(arg1) {
  return window['go']['main']['App']['SaveWebDAVConfig'](arg1);
}

export function SearchAll(arg1, arg2) {
  return window['go']['main']['App']['SearchAll'](arg1, arg2);
}

export function SetNote(arg1, arg2) {
  return window['go']['main']['App']['SetNote'](arg1, arg2);
}

export function SetUserMeta(arg1, arg2) {
  return window['go']['main']['App']['SetUserMeta'](arg1, arg2);
}

export function TestConnection(arg1) {
  return window['go']['main']['App']['TestConnection'](arg1);
}

export function Transfers() {
  return window['go']['main']['App']['Transfers']();
}

export function Unlock(arg1) {
  return window['go']['main']['App']['Unlock'](arg1);
}

export function UpdateFolderMeta(arg1, arg2) {
  return window['go']['main']['App']['UpdateFolderMeta'](arg1, arg2);
}

export function UploadPaths(arg1, arg2) {
  return window['go']['main']['App']['UploadPaths'](arg1, arg2);
}
