// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backup} from '../models';
import {main} from '../models';
import {index} from '../models';
import {config} from '../models';
import {transfer} from '../models';

export function BackupIndexNow():Promise<backup.BackupInfo>;

export function CancelTransfer(arg1:string):Promise<void>;

export function ChangePassphrase(arg1:string,arg2:string):Promise<void>;

export function CreateAccount(arg1:string):Promise<void>;

export function DeleteDrive(arg1:string):Promise<void>;

export function DeleteEntries(arg1:Array<number>,arg2:Array<number>):Promise<void>;

export function DownloadTo(arg1:Array<number>,arg2:string):Promise<number>;

export function EnsureFolder(arg1:string):Promise<number>;

export function FileInfo(arg1:number):Promise<main.FileDetail>;

export function GetAppState():Promise<main.AppState>;

export function GetCover(arg1:number):Promise<main.ThumbData>;

export function GetFileMeta(arg1:number):Promise<index.FileMeta>;

export function GetFolderMeta(arg1:number):Promise<index.FolderMeta>;

export function GetSettings():Promise<config.Settings>;

export function GetWebDAVConfig():Promise<main.WebDAVConfig>;

export function ImportFromRemote(arg1:string):Promise<backup.PullResult>;

export function ListDrives():Promise<Array<main.DriveInfo>>;

export function ListFolder(arg1:number):Promise<main.FolderView>;

export function Lock():Promise<void>;

export function MoveFiles(arg1:Array<number>,arg2:number):Promise<void>;

export function PickDir():Promise<string>;

export function PickFiles():Promise<Array<string>>;

export function PickImageFile():Promise<string>;

export function PreviewGC():Promise<main.GCReport>;

export function RenameFile(arg1:number,arg2:string):Promise<void>;

export function RenameFolder(arg1:number,arg2:string):Promise<void>;

export function ResolveConflict(arg1:string,arg2:string):Promise<void>;

export function RunGC():Promise<main.GCReport>;

export function SaveDrive(arg1:main.DriveInput):Promise<void>;

export function SaveSettings(arg1:config.Settings):Promise<void>;

export function SaveWebDAVConfig(arg1:main.WebDAVConfig):Promise<void>;

export function SearchAll(arg1:string,arg2:number):Promise<main.SearchView>;

export function SetActiveDrive(arg1:string):Promise<void>;

export function SetFileCover(arg1:number,arg2:string):Promise<boolean>;

export function SetNote(arg1:number,arg2:string):Promise<void>;

export function SetUserMeta(arg1:number,arg2:string):Promise<void>;

export function TestConnection(arg1:main.WebDAVConfig):Promise<main.TestResult>;

export function Transfers():Promise<Array<transfer.Transfer>>;

export function Unlock(arg1:string):Promise<main.UnlockResult>;

export function UpdateFileMeta(arg1:number,arg2:index.FileMetaUpdate):Promise<void>;

export function UpdateFolderMeta(arg1:number,arg2:index.FolderMetaUpdate):Promise<void>;

export function UploadPaths(arg1:Array<string>,arg2:number):Promise<number>;
